//------------------------------------------------------------------------------
// <auto-generated>
//	 This code was generated by a tool.
//
//	 Changes to this file may cause incorrect behavior and will be lost if
//	 the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace DartSassHost.Resources
{
	using System;
	using System.Globalization;
	using System.Reflection;
	using System.Resources;

	/// <summary>
	/// A strongly-typed resource class, for looking up localized strings, etc.
	/// </summary>
	internal class Strings
	{
		private static Lazy<ResourceManager> _resourceManager =
			new Lazy<ResourceManager>(() => new ResourceManager(
				"DartSassHost.Resources.Strings",
#if NET40
				typeof(Strings).Assembly
#else
				typeof(Strings).GetTypeInfo().Assembly
#endif
			));

		private static CultureInfo _resourceCulture;

		/// <summary>
		/// Returns a cached ResourceManager instance used by this class
		/// </summary>
		internal static ResourceManager ResourceManager
		{
			get
			{
				return _resourceManager.Value;
			}
		}

		/// <summary>
		/// Overrides a current thread's CurrentUICulture property for all
		/// resource lookups using this strongly typed resource class
		/// </summary>
		internal static CultureInfo Culture
		{
			get
			{
				return _resourceCulture;
			}
			set
			{
				_resourceCulture = value;
			}
		}

		/// <summary>
		/// Looks up a localized string similar to "The parameter `{0}` must be a non-empty string."
		/// </summary>
		internal static string Common_ArgumentIsEmpty
		{
			get { return GetString("Common_ArgumentIsEmpty"); }
		}

		/// <summary>
		/// Looks up a localized string similar to "The parameter '{0}' must be a non-nullable."
		/// </summary>
		internal static string Common_ArgumentIsNull
		{
			get { return GetString("Common_ArgumentIsNull"); }
		}

		/// <summary>
		/// Looks up a localized string similar to "Resource with name '{0}' is null."
		/// </summary>
		internal static string Common_ResourceIsNull
		{
			get { return GetString("Common_ResourceIsNull"); }
		}

		/// <summary>
		/// Looks up a localized string similar to "See the original error message: “{0}”."
		/// </summary>
		internal static string Common_SeeOriginalErrorMessage
		{
			get { return GetString("Common_SeeOriginalErrorMessage"); }
		}

		/// <summary>
		/// Looks up a localized string similar to "During Compilation of Sass code by using the Sass compiler a JavaScript error has occurred: {0}"
		/// </summary>
		internal static string Compiler_JsErrorDuringCompilation
		{
			get { return GetString("Compiler_JsErrorDuringCompilation"); }
		}

		/// <summary>
		/// Looks up a localized string similar to "During loading of Sass compiler error has occurred."
		/// </summary>
		internal static string Compiler_SassCompilerNotLoaded
		{
			get { return GetString("Compiler_SassCompilerNotLoaded"); }
		}

		/// <summary>
		/// Looks up a localized string similar to "Column number"
		/// </summary>
		internal static string ErrorDetails_ColumnNumber
		{
			get { return GetString("ErrorDetails_ColumnNumber"); }
		}

		/// <summary>
		/// Looks up a localized string similar to "Description"
		/// </summary>
		internal static string ErrorDetails_Description
		{
			get { return GetString("ErrorDetails_Description"); }
		}

		/// <summary>
		/// Looks up a localized string similar to "Error code"
		/// </summary>
		internal static string ErrorDetails_ErrorCode
		{
			get { return GetString("ErrorDetails_ErrorCode"); }
		}

		/// <summary>
		/// Looks up a localized string similar to "File"
		/// </summary>
		internal static string ErrorDetails_File
		{
			get { return GetString("ErrorDetails_File"); }
		}

		/// <summary>
		/// Looks up a localized string similar to "Line number"
		/// </summary>
		internal static string ErrorDetails_LineNumber
		{
			get { return GetString("ErrorDetails_LineNumber"); }
		}

		/// <summary>
		/// Looks up a localized string similar to "Message"
		/// </summary>
		internal static string ErrorDetails_Message
		{
			get { return GetString("ErrorDetails_Message"); }
		}

		/// <summary>
		/// Looks up a localized string similar to "Source fragment"
		/// </summary>
		internal static string ErrorDetails_SourceFragment
		{
			get { return GetString("ErrorDetails_SourceFragment"); }
		}

		private static string GetString(string name)
		{
			string value = ResourceManager.GetString(name, _resourceCulture);

			return value;
		}
	}
}